#!/bin/sh

. testbed/create_test_env.sh &&
if [ -z "$COPYDIR" ]; then COPYDIR=HsDataCopy; fi &&
if [ ! -d "$ROOTDIR/$COPYDIR" ]; then mkdir "$ROOTDIR/$COPYDIR"; fi &&
python ./HsGrabber.py \
    -b 15789006796024623 \
    -e 15789066796024623 \
    -c "dglo@localhost:$ROOTDIR/$COPYDIR/" \
    $*
