#!/bin/sh

source test/create_test_env.sh &&
if [ -d $ROOTDIR/copytest ]; then rm -rf $ROOTDIR/copytest; fi &&
python ./HsGrabber.py \
    -b 15789006796024623 \
    -e 15789066796024623 \
    -c dglo@localhost:$ROOTDIR/copytest/ \
    $*
